resources:   
#  - name: dbp_promoted_build_info_1
#    type: BuildInfo
#    configuration:
#      sourceArtifactory: art_v
#      buildName: backend_build
#      buildNumber: 1

  - name: dbp_promoted_build_info_1
    type: BuildInfo
    configuration:
      sourceArtifactory: rak_art
      buildName: docker_build1
      buildNumber: 1

  # Release bundle
  - name: release_bundle_1
    type: ReleaseBundle
    configuration:
      sourceDistribution: myDist
      name: demo_rb
      version: v1.0.0
 
  # Signed version of the same release bundle
  - name: signed_bundle_1
    type: ReleaseBundle
    configuration:
      sourceDistribution: myDist
      name: demo_rb
      version: v1.0.0
 
  # Distribution rules
  - name: distribution_rules_1
    type: DistributionRule
    configuration:
      sourceDistribution: myDist
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "CN"
        - "GB"

pipelines:
  - name: demo_release_mgmt
    steps:             
      - name: sign
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: release_bundle_1
          outputResources:
            - name: signed_bundle_1
 
      - name: distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signed_bundle_1
            - name: distribution_rules_1
